### ISSUE TITLE
Error in smsmapper.php and Appframwork

### ISSUE THREAD

**Issue by enoch85** [nerzhul/ocsms#39] opened 2015-01-31 18:25 UTC
I reeally wonder what this is:

```
{"app":"PHP","message":"Undefined index: 3 at \/var\/www\/owncloud\/apps\/ocsms\/db\/smsmapper.php#45","level":3,"time":"2015-01-30T00:20:43+00:00"}
{"app":"PHP","message":"Undefined index: 3 at \/var\/www\/owncloud\/apps\/ocsms\/db\/smsmapper.php#45","level":3,"time":"2015-01-30T01:20:34+00:00"}
{"app":"PHP","message":"Undefined index: 3 at \/var\/www\/owncloud\/apps\/ocsms\/db\/smsmapper.php#45","level":3,"time":"2015-01-30T04:20:35+00:00"}
{"app":"PHP","message":"Undefined index: 3 at \/var\/www\/owncloud\/apps\/ocsms\/db\/smsmapper.php#45","level":3,"time":"2015-01-30T07:21:05+00:00"}
{"app":"PHP","message":"Undefined index: 3 at \/var\/www\/owncloud\/apps\/ocsms\/db\/smsmapper.php#45","level":3,"time":"2015-01-30T10:22:06+00:00"}
{"app":"PHP","message":"Undefined index: 3 at \/var\/www\/owncloud\/apps\/ocsms\/db\/smsmapper.php#45","level":3,"time":"2015-01-30T13:22:06+00:00"}
{"app":"PHP","message":"Undefined index: 3 at \/var\/www\/owncloud\/apps\/ocsms\/db\/smsmapper.php#45","level":3,"time":"2015-01-30T16:22:08+00:00"}
{"app":"PHP","message":"call_user_func() expects parameter 1 to be a valid callback, class 'OCA\\OcSms\\Db\\Config' not found at \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php#250","level":3,"time":"2015-01-30T18:10:33+00:00"}
{"app":"PHP","message":"call_user_func() expects parameter 1 to be a valid callback, class 'OCA\\OcSms\\Db\\Config' not found at \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php#250","level":3,"time":"2015-01-30T18:10:37+00:00"}
{"app":"PHP","message":"call_user_func() expects parameter 1 to be a valid callback, class 'OCA\\OcSms\\Db\\Config' not found at \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php#250","level":3,"time":"2015-01-30T18:10:39+00:00"}
{"app":"PHP","message":"call_user_func() expects parameter 1 to be a valid callback, class 'OCA\\OcSms\\Db\\Config' not found at \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php#250","level":3,"time":"2015-01-30T18:11:05+00:00"}
{"app":"PHP","message":"call_user_func() expects parameter 1 to be a valid callback, class 'OCA\\OcSms\\Db\\Config' not found at \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php#250","level":3,"time":"2015-01-30T18:11:07+00:00"}
{"app":"PHP","message":"call_user_func() expects parameter 1 to be a valid callback, class 'OCA\\OcSms\\Db\\Config' not found at \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php#250","level":3,"time":"2015-01-30T18:11:23+00:00"}
{"app":"PHP","message":"call_user_func() expects parameter 1 to be a valid callback, class 'OCA\\OcSms\\Db\\Config' not found at \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php#250","level":3,"time":"2015-01-30T18:11:24+00:00"}
{"app":"PHP","message":"call_user_func() expects parameter 1 to be a valid callback, class 'OCA\\OcSms\\Db\\Config' not found at \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php#250","level":3,"time":"2015-01-30T18:11:26+00:00"}
{"app":"PHP","message":"Undefined index: 3 at \/var\/www\/owncloud\/apps\/ocsms\/db\/smsmapper.php#45","level":3,"time":"2015-01-30T19:22:08+00:00"}
{"app":"PHP","message":"Undefined index: 3 at \/var\/www\/owncloud\/apps\/ocsms\/db\/smsmapper.php#45","level":3,"time":"2015-01-30T22:22:35+00:00"}
```

Running 1.4.2.

**Comment by martin-rueegg** [comment] 2015-02-12 21:47
### Investigation
db/smsmapper.php#45 reads:
```
$mbox = SmsMapper::$mailboxNames[$row["sms_mailbox"]];
```

SmsMapper::$mailboxNames contains the following entries:
```
private static $mailboxNames = array(0 => "inbox", 1 => "sent", 2 => "drafts");
```
so 0-2 are valid indices. the data **$row["sms_mailbox"]** is comming from the db table \*PREFIX\*ocsms_smsdatas

so any value is inserted either by the sync client (via **writeToDB()**) or by the user directly to the db.

looking at the sync client, there are the follwing four codes:
<https://github.com/nerzhul/ownCloud-SMS-App/blob/master/src/fr/unix_experience/owncloud_sms/enums/MailboxID.java>
```
public enum MailboxID {
INBOX,
SENT,
DRAFTS,
ALL,
}
```
so, values 0-3.

could 3 be the issue? <https://github.com/nerzhul/ownCloud-SMS-App/blob/master/src/fr/unix_experience/owncloud_sms/engine/SmsFetcher.java#L55> shows, that in the first place (fetchAllMessages) only values 0-2 are used, and in the second place (bufferizeMailboxMessages) only values 0-2 are accepted.
```
	public SmsFetcher(Context ct) {
		_lastMsgDate = (long) 0;
		_context = ct;
		
		_existingInboxMessages = null;
		_existingSentMessages = null;
		_existingDraftsMessages = null;
	}
	
	public JSONArray fetchAllMessages() {
		_jsonDataDump = new JSONArray();
		bufferizeMailboxMessages(MailboxID.INBOX);
		bufferizeMailboxMessages(MailboxID.SENT);
		bufferizeMailboxMessages(MailboxID.DRAFTS);
		return _jsonDataDump;
	}
	
	private void bufferizeMailboxMessages(MailboxID mbID) {
		String mbURI = mapMailboxIDToURI(mbID);
		
		if (_context == null || mbURI == null) {
			return;
		}
		
		if (mbID != MailboxID.INBOX && mbID != MailboxID.SENT &&
			mbID != MailboxID.DRAFTS) {
			Log.e(TAG,"Unhandled MailboxID " + mbID.ordinal());
			return;
		}
```

not sure, if in java arguments (enum) are passed as reference or by value. in case of a reference there could only be that android.net.Uri is changing the mbox value. but i don't think so.

so in the current code i can't find a reason why there should be an wrong index in mbox.

### what's next?
has the error been confirmed? is it still happening? what are the client/server versions of the app and the oc-server?

**Comment by enoch85** [comment] 2015-02-12 22:58
### Server configuration

Ubuntu Server 12.04

**Database:**
Apache/2.2.22 (Ubuntu)
MySQL: 5.5.41
PHP version:
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

**ownCloud version: (see ownCloud admin page)**
8.0
*Updated from an older ownCloud or fresh install:*
Updated from 5, 6, 7

**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
First Run Wizard
Full Text Search
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions
Video Viewer
ownCloud SMS

**Are you using external storage, if yes which one: local/smb/sftp/...**
No
**Are you using encryption: yes/no**
No

### Client configuration

**Browser:**
Version 39.0.2171.71 m
**Operating system:**
Windows 8.1
**Sync Client**
1.7.1 stable

**Comment by enoch85** [comment] 2015-02-12 22:59
And yes, still happening.

**Comment by martin-rueegg** [comment] 2015-02-12 23:11
would you mind to dump:
```
SELECT sms_mailbox
FROM `oc_ocsms_smsdatas`
GROUP BY sms_mailbox
```

**Comment by enoch85** [comment] 2015-02-12 23:44
@martin-rueegg 

![image](https://cloud.githubusercontent.com/assets/4511254/6179423/6562ca9c-b319-11e4-9614-a4022e8e26a1.png)

**Comment by martin-rueegg** [comment] 2015-02-12 23:54
great! now, i would be interested in the records with `sms_mailbox = 3`. please check if you can share some data of it. 3 is the enum for `MailboxID.ALL`.

could it be possible that the data has been synced to the server with an older client app?

as a workaround you could update the given records to have sms_mailbox = 2. the error should then be disappearing while you still can identify the records (having a mbox value of 2 instead of 3).

1. send excemple data
2. check if error is gone when sms_mailbox set to 2
```
UPDATE `oc_ocsms_smsdatas` SET `sms_mailbox` =2 WHERE `sms_mailbox` =3
```

**Comment by enoch85** [comment] 2015-02-13 00:08
@martin-rueegg MySQL shell isn't my expertise. ;) Please send the commands and I will execute them.

**Comment by martin-rueegg** [comment] 2015-02-13 00:13
###    send excemple data

if there is no sensitive data (please check or edit data):
```
SELECT * FROM `oc_ocsms_smsdatas` WHERE `sms_mailbox` = 3
```

otherwise avoid the message body using:
```
SELECT `id`, `user_id`, `added`, `lastmodified`, `sms_id`, `sms_address`, `sms_date`, `sms_flags`, `sms_type` FROM `oc_ocsms_smsdatas` WHERE `sms_mailbox` = 3
```

####  check if error is gone when sms_mailbox set to 2
```
UPDATE `oc_ocsms_smsdatas` SET `sms_mailbox` =2 WHERE `sms_mailbox` =3
```
then check logs while syncing.

**Comment by enoch85** [comment] 2015-02-13 00:17
Checked, and sms_mailbox 3 is empty!

Will do a resync and put the output here.

**Comment by martin-rueegg** [comment] 2015-02-13 00:23
well, according to your first output, there is at least one record with sms_mailbox = 3. pleas still past the output of:
```
SELECT sms_mailbox, count(*)
FROM `oc_ocsms_smsdatas`
GROUP BY sms_mailbox
```
and
```
SELECT `id`, `user_id`, `added`, `lastmodified`, `sms_id`, `sms_address`, `sms_date`, `sms_flags`, `sms_type`
FROM `oc_ocsms_smsdatas`
WHERE `sms_mailbox` not in (0, 1)
```

**Comment by enoch85** [comment] 2015-02-13 00:30
I did the workaround as you said.

```
SQL-resultat

Värd: localhost
Databas: owncloud
Skapad: 13 feb 2015 kl 01:28
Genererad av: phpMyAdmin 3.4.10.1deb1 / MySQL 5.5.41-0ubuntu0.12.04.1
SQL-fråga: SELECT sms_mailbox, count(*) FROM `oc_ocsms_smsdatas` GROUP BY sms_mailbox LIMIT 0, 30 ; 
Rader: 3

sms_mailbox	count(*)
0	1218
1	1421
2	2
```

```
SQL-resultat

Värd: localhost
Databas: owncloud
Skapad: 13 feb 2015 kl 01:29
Genererad av: phpMyAdmin 3.4.10.1deb1 / MySQL 5.5.41-0ubuntu0.12.04.1
SQL-fråga: SELECT `id`, `user_id`, `added`, `lastmodified`, `sms_id`, `sms_address`, `sms_date`, `sms_flags`, `sms_type` FROM `oc_ocsms_smsdatas` WHERE `sms_mailbox` not in (0, 1) LIMIT 0, 30 ; 
Rader: 2

id	user_id	added	lastmodified	sms_id	sms_address	sms_date	sms_flags	sms_type
273978	enoch	0000-00-00 00:00:00	0000-00-00 00:00:00	2530	+46704330831	1422056574639	01	1
1067830	enoch	0000-00-00 00:00:00	0000-00-00 00:00:00	2960	+46737451044	1423081307418	01	1
```

**Comment by martin-rueegg** [comment] 2015-02-13 00:34
ok.

1. do you still see the error?
2. any ideas about the two messages? do you remember them in the sense, that they have been created by an other app then the other smses you created? or have they not been sent successfully? or anything similar?

do you have a rooted phone? can you open your sms-database on the phone and see what the records for messages with id 2530 and 2960 are? are they MMS?

**Comment by enoch85** [comment] 2015-02-13 00:48
No more error. :D 

I have a Nexus 5, not rooted. Sorry.

New error though when opening the Web UI SMS:

```
Error	PHP	Undefined offset: 0 at /var/www/owncloud/apps/contacts/lib/backend/shared.php#90	2015-02-13T00:46:59+00:00
Error	PHP	Undefined offset: 0 at /var/www/owncloud/apps/contacts/lib/backend/shared.php#90	2015-02-13T00:46:59+00:00
Error	PHP	Undefined offset: 0 at /var/www/owncloud/apps/contacts/lib/backend/shared.php#90	2015-02-13T00:46:59+00:00
Error	PHP	Undefined offset: 0 at /var/www/owncloud/apps/contacts/lib/backend/shared.php#90	2015-02-13T00:46:59+00:00
Error	PHP	Undefined offset: 0 at /var/www/owncloud/apps/contacts/lib/backend/shared.php#90	2015-02-13T00:46:59+00:00
```

**Comment by martin-rueegg** [comment] 2015-02-13 01:06
well, this might be a "new" error, or an error that is unrelated to the first one. but since the first error is now "solved", the program continues and runs in a second one.

obviously you have multiple contact address books. if i understand the code of `[lib/backend/shared.php](https://github.com/owncloud/contacts/blob/master/lib/backend/shared.php#L90)` correctly, you might even have a shared addressbook.

not sure, if this is an ocsms issue. see (https://github.com/nerzhul/ownCloud-SMS-App/issues/23) on the comment regarding multiple addressbooks.

**Comment by enoch85** [comment] 2015-02-13 01:08
No, one adresssbook, but other adressbooks for other users on the server, so maybe that's the issue?

Thank you for helping out anyway! Any permanent fix for this in next release?

**Comment by martin-rueegg** [comment] 2015-02-13 01:19
well, it is not sure, where the error came from. so the issue is not "fixed"! :worried: 

the SQL we run was only a workaround to see if my assumption is correct. according to the current code i cannot understand, where this mbox=3 came from! that's why i asked if you can recognize the messages you found by the sql-command:
```
SELECT *
FROM `oc_ocsms_smsdatas`
WHERE `sms_mailbox` not in (0, 1)
```
it might help to see the data on your phone. but i have no idea how to access it, if your phone is not rooted. one option would be to delete all the messages on your server and sync them again. i could send you the SQL for purging the messages on your server. all the SMS would then be re-uploaded to the server again. you would have to stop the sync service on the phone, and then reactivate it.

it would be interesting in the sense that we could figure out if it was an one-time error (when synching the first time) ore if the data in your phone are special (if the error will pop up again after resync).

ready?

i guess if you don't have any shared contacts form other users, it should not be a problem. but i did not dig into that so far. (today is my first day in OC and ocsms coding!)

**Comment by enoch85** [comment] 2015-02-13 01:32
What table do I drop to redownload?

**Comment by enoch85** [comment] 2015-02-13 01:35
Btw, it's regular SMS not MMS.

**Comment by martin-rueegg** [comment] 2015-02-13 02:07
read the instructions. in case of questions pls don't hesitate to ask.

**1** in phpmyadmin select the table `oc_ocsms_user_datas`
**2** on the top menu select `Operations`
**3** on the right hand side use the copy table function to copy the table with structure and data (default) to `oc_ocsms_user_datas_sav` (we will use that table later to restore the message-read-information).
**4** check that the new table `oc_ocsms_user_datas_sav` exists and has records
**5** repeat steps 1 to 4 for the `oc_ocsms_smsdatas` -> `oc_ocsms_smsdatas_sav` (just for the sake of safety)
**6** turn off sync on mobile 
**7** run the following SQL commands (this will empty the two tables completely):
```
TRUNCATE oc_ocsms_smsdatas;
TRUNCATE oc_ocsms_user_datas;
```
**8** turn on sync on mobile
**9** wait for sync to complete
**10** check if messages appear in web UI (will be all unread. don't worry)
**11** restart sync on mobile in order to do a second sync (the error won't appear during first sync). and check the log files.
**12** run the following SQL commands and paste the output:
```
SELECT sms_mailbox, count(*)
FROM `oc_ocsms_smsdatas`
GROUP BY sms_mailbox;

SELECT `id`, `user_id`, `added`, `lastmodified`, `sms_id`, `sms_address`, `sms_date`, `sms_flags`, `sms_type`
FROM `oc_ocsms_smsdatas`
WHERE `sms_mailbox` not in (0, 1)
```
**13** run the following command to restore the read-message-info:
```
INSERT INTO `oc_ocsms_user_datas`(`user_id`, `datakey`, `datavalue`)
SELECT * FROM `oc_ocsms_user_datas_sav` WHERE 1
```
**14** check in web-ui if messages are marked as read again.

i did everything here on my side. so it should be safe.

**Comment by enoch85** [comment] 2015-02-13 02:20
12. 
```
sms_mailbox	count(*)
0	1119
1	1301
```

```
SELECT  `id` ,  `user_id` ,  `added` ,  `lastmodified` ,  `sms_id` ,  `sms_address` ,  `sms_date` ,  `sms_flags` ,  `sms_type` 
FROM  `oc_ocsms_smsdatas` 
WHERE  `sms_mailbox` NOT 
IN ( 0, 1 ) 
LIMIT 0 , 30
```

Jumped a few steps, didn´t create .sav

**Comment by enoch85** [comment] 2015-02-13 02:21
Now it's time for bed. Good night :)

**Comment by martin-rueegg** [comment] 2015-02-13 02:35
well, there seems to be either some messages missing or the sync is not complete. before the re-synch you reported:

> sms_mailbox count(*)
> 0   1218
> 1   1421
> 3   2

now you only had:
> sms_mailbox count(*)
> 0   1119
> 1   1301

no missing approx 200 msg.

how about: 
```
SELECT  `id` ,  `user_id` ,  `sms_id` ,  `sms_address` ,  `sms_date` ,  `sms_flags` ,  `sms_type` 
FROM  `oc_ocsms_smsdatas` 
WHERE  `sms_id` IN ( 2530, 2960 ) 
```
can you (tomorrow) post the output?

> Now it's time for bed. Good night :)

jep. you're right! same, same.

**Comment by nerzhul** [comment] 2015-02-13 06:08
Hi.
Thanks for your investigations. MMS aren't read and synced with owncloud

**Comment by enoch85** [comment] 2015-02-13 11:03
I deleted some messages on the phone, that's why. :)

Med vänlig hälsning
Daniel Hansson

www.en0ch.se

Skickat från Google Nexus 5
Den 13 feb 2015 03:35 skrev "Martin Rüegg" <notifications@github.com>:

**Comment by martin-rueegg** [comment] 2015-02-13 11:20
yeah, i guess so. hope you don't mind not having them on the server any more.

still, could you check if the two messages that caused the error are still in your message set? if they're gone now, we will have to close this issue, as there is no way to find out, what was the cause of it. in fact, even if the messages are there we wouldn't be able to do so.

i see two possible reasons for the issue:
* the original data of the two records was quite particular so that during sync they somehow got the mbox=3
* something just went wrong once, not based on the original data. so the error can't be reproduced.

either way we can not reproduce the error any more. i have reviewed the code (except for the android libraries) and could not figure out, where the number `3` could have originated from.  thus i would suggest to close the issue for now.

**Comment by nerzhul** [comment] 2015-02-13 11:33
Thanks for your report and your time. I think this 3 comes from the old version which doesn't filter types

**Comment by enoch85** [comment] 2015-02-13 11:52
Thanks for helping out!

**Comment by martin-rueegg** [comment] 2015-02-13 11:56
welcome. :-)

well then, if an old version (or a user, in an other case) could have entered wrong values, would it then make sense to change [getAllIds()](https://github.com/nerzhul/ocsms/blob/master/db/smsmapper.php#L38) in one of the following way?
- [ ] only select messages with known mbox types
   ([Line 40](https://github.com/nerzhul/ocsms/blob/master/db/smsmapper.php#L40):  `'WHERE user_id = ? AND sms_mailbox IN (' . implode(', ', array_keys(SmsMapper::$mailboxNames)) . ')'`
    (yes, we would use a parameter `?`. this here is just a draft)
- [ ] check if `array_key_exists($row["sms_mailbox"], SmsMapper::$mailboxNames)` ([Line 45](https://github.com/nerzhul/ocsms/blob/master/db/smsmapper.php#L45)) and then act accordingly (e.g. updating the mbox in database to a valid default (suggestion: 2 for 'drafts'))

the first variant would cause the client to resend the given message. thus [writeToDB()](https://github.com/nerzhul/ocsms/blob/master/db/smsmapper.php#L233) would have to be altered in order to update existing entries.

**Comment by nerzhul** [comment] 2015-02-13 12:56
I will modify the sync process to improve the API in next app version , we can think about a modification for sync process V2

**Comment by enoch85** [comment] 2015-02-15 13:33
```
{"reqId":"cfc92de7499534564c57fab66d28f999","remoteAddr":"109.58.144.140","app":"PHP","message":"Undefined offset: 3 at \/var\/www\/owncloud\/apps\/ocsms\/db\/smsmapper.php#45","level":3,"time":"2015-02-14T06:40:52+00:00"}
```

Still same error.

**Comment by martin-rueegg** [comment] 2015-02-15 13:58
@enoch85 , what is the version of your sms-sync client? the current v0.17.0?

can you tell us something about the nature of the sms found by
```
SELECT  *
FROM  `oc_ocsms_smsdatas` 
WHERE  `sms_mailbox` NOT 
IN ( 0, 1 ) 
```
guess we still should think about one of the solutions suggested in https://github.com/nerzhul/ocsms/issues/39#issuecomment-74243202

**Comment by enoch85** [comment] 2015-02-15 14:10
@martin-rueegg The versions are 1.17.0 and 1.4.2.

The SQL didn't give any results.

**Comment by martin-rueegg** [comment] 2015-02-15 14:20
@enoch85, where did you get this version string ` 1.17.0` from? are we sure we're both talking about the [owncloud SMS android client](https://play.google.com/store/apps/details?id=fr.unix_experience.owncloud_sms)?

**Comment by enoch85** [comment] 2015-02-15 14:28
![image](https://cloud.githubusercontent.com/assets/4511254/6203542/37d4bada-b527-11e4-99b5-989e9641967d.png)

**Comment by martin-rueegg** [comment] 2015-02-15 14:36
as to my https://github.com/nerzhul/ocsms/issues/39#issuecomment-74159945 the index is coming from the db table `*PREFIX*ocsms_smsdatas` (default `oc_ocsms_smsdatas`). the `sms_mailbox` field is a smallint and does not allow NULL values in `sms_mailbox`. so how could the error be thrown, if the query
```
SELECT  *
FROM  `oc_ocsms_smsdatas` 
WHERE  `sms_mailbox` NOT 
IN ( 0, 1 ) 
```
doesn't return any results? :hushed: 

@enoch85, do you have any  `dbtableprefix` in your `config.php`, if so, what's it's value?

regarding client version: according to your screenshot it reads v**0**.17.0. that's fine. tnx.

**Comment by martin-rueegg** [comment] 2015-02-15 14:38
@enoch85 please run again
```
SELECT sms_mailbox, count(*)
FROM `oc_ocsms_smsdatas`
GROUP BY sms_mailbox;
```

**Comment by enoch85** [comment] 2015-02-15 14:40
sms_mailbox	count(*)
0	1125
1	1309

**Comment by enoch85** [comment] 2015-02-15 14:41
Hmm, look at the time. Maybe this is before we fixed it?

**Comment by martin-rueegg** [comment] 2015-02-15 14:47
what time? we havn't fixed anything yet. we have just re-synced all messages in order to see, if the android client is sending some "special" data.
according to the code, the data causing the error comes from the database. the data in the database comes from the client. so my idea was to find out, where the erroneous data is coming from.
now, according to your information, there is no erroneous data in your database. so the error "is not possible".
ah, by "time" you mean the time of the error message? it states "2015-02-14T06:40:52+00:00". the "fix" we did on 2015-02-13.
it's very weird.

**Comment by martin-rueegg** [comment] 2015-02-15 14:48
sorry for asking: are you sure you run the SQL on the same database, the oc instance creating the errorlog is accessing as well?

**Comment by enoch85** [comment] 2015-02-15 14:55
@martin-rueegg haha, yes I'm sure.

**Comment by martin-rueegg** [comment] 2015-02-15 15:09
@nerzhul just noticed, that the following functions in the client *do not* check the mailbox. so there could be a mbox=3 message flawing to the server, right?
see:
* [getLastMessage()](https://github.com/nerzhul/ownCloud-SMS-App/blob/0.17.0/src/fr/unix_experience/owncloud_sms/engine/SmsFetcher.java#L127)
* [bufferizeMessagesSinceDate()](https://github.com/nerzhul/ownCloud-SMS-App/blob/0.17.0/src/fr/unix_experience/owncloud_sms/engine/SmsFetcher.java#L191)
wouldn't it make sense to merge these two functions with the third of the same type?
* [bufferizeMailboxMessages](https://github.com/nerzhul/ownCloud-SMS-App/blob/0.17.0/src/fr/unix_experience/owncloud_sms/engine/SmsFetcher.java#L48)
as they mainly differ in the way they select the messages
* [bufferizeMailboxMessages](https://github.com/nerzhul/ownCloud-SMS-App/blob/0.17.0/src/fr/unix_experience/owncloud_sms/engine/SmsFetcher.java#L48) select **all not existing on the server**
* [getLastMessage()](https://github.com/nerzhul/ownCloud-SMS-App/blob/0.17.0/src/fr/unix_experience/owncloud_sms/engine/SmsFetcher.java#L127) selects **all but only saves the last of the result**
* [bufferizeMessagesSinceDate()](https://github.com/nerzhul/ownCloud-SMS-App/blob/0.17.0/src/fr/unix_experience/owncloud_sms/engine/SmsFetcher.java#L191) saves **all with date gt x**
if the second parameter `Long sinceDate` would be optional (not knowing how to do this in java), then we could use one single function under the thee following conditions:
* [bufferizeMailboxMessages](https://github.com/nerzhul/ownCloud-SMS-App/blob/0.17.0/src/fr/unix_experience/owncloud_sms/engine/SmsFetcher.java#L48) sets `sinceDate = 0`
* [bufferizeMessagesSinceDate()](https://github.com/nerzhul/ownCloud-SMS-App/blob/0.17.0/src/fr/unix_experience/owncloud_sms/engine/SmsFetcher.java#L191) sets `sinceDate` the same way it does it now
* [getLastMessage()](https://github.com/nerzhul/ownCloud-SMS-App/blob/0.17.0/src/fr/unix_experience/owncloud_sms/engine/SmsFetcher.java#L127) leaves `sinceDate` alone, defaulting it to NULL or EMPTY or alike.
this would ease the maintenance of the code, IMHO.

**Comment by martin-rueegg** [comment] 2015-02-15 15:14
@enoch85, i know it was a funny question. but sometimes even Pros overlook a tiny little thing. at least i do. :smile: 

i really don't know what to say. according to the code and your data i simply cannot understand why the error is occuring. can it be something in \OCP\DB::prepare, so that the result array is "strange"?

i'm stuck.

**Comment by nerzhul** [comment] 2015-02-15 15:15
In fact we trust the database content, because the only write is done by sync which permits only type 1 and 2. Could you provide a PR with the optimization you'll find we could discuss there.

**Comment by martin-rueegg** [comment] 2015-02-15 15:28
re: optimization: ok, i can do so, but please tell me how to define a optional parameter with a default value in java. (not sure if i'll get there today though ...)

re: database write

if either [bufferizeMessagesSinceDate()](https://github.com/nerzhul/ownCloud-SMS-App/blob/0.17.0/src/fr/unix_experience/owncloud_sms/engine/SmsFetcher.java#L191) (//Used by ConnectivityChanged Event) or  [getLastMessage()](https://github.com/nerzhul/ownCloud-SMS-App/blob/0.17.0/src/fr/unix_experience/owncloud_sms/engine/SmsFetcher.java#L127) (// Used by Content Observer) are called with MailboxID mbID = 3 then [mapMailboxIDToURI()](https://github.com/nerzhul/ownCloud-SMS-App/blob/0.17.0/src/fr/unix_experience/owncloud_sms/engine/SmsFetcher.java#L265) returns `content://sms` and an mbID.ordinal() returns 3 (which is stored to mbox in the JSON) which in turn might be wrong as to my understanding `content://sms` would return any mailbox (inbox, sent, draft, ...). instead of mbID.ordinal(), the actual value in the record shoud be used.

and at the server we [safe](https://github.com/nerzhul/ocsms/blob/master/db/smsmapper.php#L265) any value coming from the client to the db. so a 3 could result as shown above.

**Comment by martin-rueegg** [comment] 2015-02-15 15:30
([found](http://stackoverflow.com/questions/965690/java-optional-parameters) about optional parameters)

**Comment by nerzhul** [comment] 2015-02-16 14:04
you are right. I found where the issue can happen.
It's in SmsObserver.onChange, we check the last message for all mailboxes when the connectivity changed. And then if the mailbox is other than the required mailboxes, it worked. I need to fix the issue now, and i publish a patch on Google Play Store soon.

**Closed** 2015-02-16 14:14 UTC
Labels: bug

**Comment by martin-rueegg** [comment] 2015-02-16 14:26
i'll try to propose the merge of the functions as discussed previously. so we will only have one main function to maintain. i'll do it today. could you wait with sending the patch to google play store?
btw: i think we should do a check still on the server side as well, as we should never trust the data coming from the internet. someone might build a compatibe client and use the server-api.

**Comment by nerzhul** [comment] 2015-02-16 14:27
No release for google play store at this time. Server must be tagged before client, to support the new bugfixes/features.
